# Generated by Django 5.2.12 on 2026-03-28 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kpi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tasks_done', models.PositiveIntegerField(default=0)),
                ('tasks_total', models.PositiveIntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Низький'), ('medium', 'Середній'), ('high', 'Високий')], default='low', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'period')},
            },
        ),
    ]
