# Generated by Django 6.0.3 on 2026-04-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reviewer', models.CharField(max_length=200)),
                ('employee_name', models.CharField(max_length=200)),
                ('team', models.CharField(blank=True, max_length=50)),
                ('responsibility', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('teamwork', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('learning_speed', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('engineering', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('tech_skills', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('availability', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('vibe', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'team', 'employee_name'],
            },
        ),
        migrations.DeleteModel(
            name='Performance',
        ),
    ]
