# Generated by Django 5.2.12 on 2026-03-28 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('nda', 'NDA'), ('contract', 'Контракт'), ('policy', 'Політика'), ('other', 'Інше')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('signed', 'Підписано'), ('pending', 'Очікує'), ('rejected', 'Відмова')], default='pending', max_length=20)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
