# Generated by Django 6.0.3 on 2026-04-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookiesChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('team', models.CharField(blank=True, max_length=50)),
                ('year', models.PositiveIntegerField(default=2026)),
                ('january', models.BooleanField(default=False)),
                ('february', models.BooleanField(default=False)),
                ('march', models.BooleanField(default=False)),
                ('april', models.BooleanField(default=False)),
                ('may', models.BooleanField(default=False)),
                ('june', models.BooleanField(default=False)),
                ('july', models.BooleanField(default=False)),
                ('august', models.BooleanField(default=False)),
                ('september', models.BooleanField(default=False)),
                ('october', models.BooleanField(default=False)),
                ('november', models.BooleanField(default=False)),
                ('december', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['team', 'employee_name'],
                'unique_together': {('employee_name', 'year')},
            },
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
