# Generated by Django 5.2.12 on 2026-03-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=150)),
                ('team', models.CharField(choices=[('dev', 'Development'), ('design', 'Design'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('hr', 'HR'), ('qa', 'QA'), ('pm', 'PM')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Активний'), ('vacation', 'Відпустка'), ('remote', 'Віддалено'), ('probation', 'Випробувальний'), ('dismissed', 'Звільнений')], default='active', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('hire_date', models.DateField()),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('avatar_color', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
