# Generated by Django 6.0.3 on 2026-03-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('onboarding', 'Onboarding'), ('active', 'Працює'), ('vacation', 'Відпустка'), ('offboarding', 'До офбордингу'), ('dismissed', 'Покинув команду')], default='active', max_length=20),
        ),
    ]
