# Generated by Django 6.0.3 on 2026-03-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['team', 'last_name']},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.AddField(
            model_name='employee',
            name='calendly_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hr_responsible',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='nda_status',
            field=models.CharField(blank=True, choices=[('signed', 'Підписано'), ('not_signed', 'Не підписано'), ('none', '—')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='recruiter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('', '—'), ('low', 'Низький'), ('medium', 'Середній'), ('high', 'Високий')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='status_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.CharField(max_length=50),
        ),
    ]
