# Generated by Django 6.0.3 on 2026-04-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_employee_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
